- name: Configure Raspberry Pis for theater network
  hosts: pis
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ ansible_env.USER }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"

    - name: Copy GitHub SSH public key to Pi
      copy:
        src: ~/.ssh/github_rpi.pub
        dest: "/home/{{ ansible_env.USER }}/.ssh/authorized_keys"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0600'


    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system if required
      reboot:
        msg: "Rebooting after upgrade"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists
