- name: Configure static IP for eth0
  hosts: pis
  become: true
  tasks:
    - name: Configure eth0 with static IP
      blockinfile:
        path: /etc/dhcpcd.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK eth0"
        block: |
          interface eth0
          static ip_address={{ static_ip }}/24
          static routers={{ static_router }}
          static domain_name_servers={{ static_dns }}

    - name: Restart dhcpcd service
      service:
        name: dhcpcd
        state: restarted
